In [3]:
%matplotlib inline
import pandas as pd
import numpy as np
import seaborn as sns
import ast
sns.set()

from pyathena import connect

In [9]:
conn = connect(s3_staging_dir='s3://aws-athena-query-results-415718651610-us-east-1', region_name='us-east-1')
data = pd.read_sql("SELECT type,CAST(item[1] as JSON) as item,CAST(host[1] as JSON) as host, CAST(trigger[1] as JSON) as trigger, CAST(event[1] as JSON) as event, usc_das_id  FROM das.event limit 1", conn)

In [10]:
data.describe()

,type,item,host,trigger,event,usc_das_id
count,1,1,1,1,1,0.0
unique,1,1,1,1,1,0.0
top,event_recovery,"[1, 1852552, , Chamados com TTS abaixo de 15mi...","[OTRS, OTRS, 172.16.255.202]","[Information, , TRIGGER.NSEVERITY}, Unirede, 0...","[RESOLVED, 1 , , 11:31:55, 2019.03.30, 3623759...",NaN
freq,1,1,1,1,1,NaN

In [6]:
data.head()

,type,item,host,trigger,event,usc_das_id
0,event,"[811.52 Kbps, 974598, , Tráfego de Saida Gigab...","[router106, LBS-f106-router, 172.17.106.1]","[Average, , 3, Lebes - Filiais, Lebes - Geral,...","[PROBLEM, 3, , 18:26:17, 2019.04.02, 363712005...",gGK07aOLxP5n6Mmn97WQ6rNvlbBkYZeA

In [8]:
print("item")
print("item value = " + data.item[0][0])
print("item id = " + data.item[0][1])
print("item descr = " + data.item[0][2])
print("item name = " + data.item[0][3])

print("\nhost:")
print("host address = " + data.host[0][0])
print("host name= " + data.host[0][1])
print("host conn= " + data.host[0][2])

print("\ntrigger:")
print("trigger severity = " + data.trigger[0][0])
print("trigger descr = " + data.trigger[0][1])
print("trigger nseverity = " + data.trigger[0][2])
print("trigger hostgroup_name= " + data.trigger[0][3])
print("trigger value = " + data.trigger[0][4])
print("trigger id = " + data.trigger[0][5])
print("trigger name = " + data.trigger[0][6])


print("\nevent:")
print("event status = " + data.event[0][0])
print("event severity = " + data.event[0][1])
print("event tags = " + data.event[0][2])
print("event time = " + data.event[0][3])
print("event date = " + data.event[0][4])
print("event id = " + data.event[0][5])
print("event name = " + data.event[0][6])

item
item value = 811.52 Kbps
item id = 974598
item descr =
item name = Tráfego de Saida GigabitEthernet0/0

host:
host address = router106
host name= LBS-f106-router
host conn= 172.17.106.1

trigger:
trigger severity = Average
trigger descr =
trigger nseverity = 3
trigger hostgroup_name= Lebes - Filiais, Lebes - Geral, LEBES - LINKS SMS
trigger value = 1
trigger id = 501275
trigger name = router106: Tráfego de Saída GigabitEthernet0/0 maior que 70%

event:
event status = PROBLEM
event severity = 3
event tags =
event time = 18:26:17
event date = 2019.04.02
event id = 363712005
event name = router106: Tráfego de Saída GigabitEthernet0/0 maior que 70%